>>> #import module
... #from module import class
... 
>>> #from package import module
... 
>>> #from package import module1,module2
... 
>>> #from module import class1.class2
... #from package import *
... 
>>> #from module import *
